language: java
jdk:
  - openjdk17

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - "./gradlew clean build -x test"

notifications:
  email:
    recipients:
      - jk47wee@gmail.com